kobotoolbox/docs

- source/conf.py
Plus print copyright year from current date
> Expand only current content toc

- source/enketo.md
* Linked with existing articles.
* Linked with Enketo blog.
* Update broken link.
* Minor updates.
> Closing #40 - minor updates

- source/restrict_responses.md
> Closing #49 - Formatting updates

- source/troubleshooting_webforms.md
* Link to appropriate articles
* Minor updates
> Closing #44 - Minor updates 

- source/data_through_webforms.md
* Update link to other support article
* Update added feature description Online-only (once per respondent) in the existing document
> Closing #42 - Minor updates

- source/troubleshooting_webforms.md
@joshuaberetta, it seems that we somehow missed the broken link while updating this support article previously.
> Closing #52 - fixed broken link

- source/photo_download.md
* Update formula:
`=CONCATENATE(HYPERLINK("https://kc.humanitarianresponse.info/attachment/original?media_file=username/attachments/"),A2)`
* Minor formatting
> Closing #78 - Updated formula and minor formatting

- source/hipaa_compliance.md
No need to advertise AWS; emphasize that compliance depends on the hosting solution more than the software
Context: https://chat.kobotoolbox.org/#narrow/stream/6-Support/topic/HIPAA
> Clarify HIPAA explanation

- requirements.txt
- source/conf.py
> Support Markdown tables

- source/new_form.md
> Note form-builder limitations

- source/matrix_response.md
> Fix and update `matrix_response` page xlsform example

- source/kobocollect_on_android_basic.md
* Changed title
* Fixed broken link
@joshuaberetta, @c6reid cc: @Ig-Rebollo please be informed that I have updated this article as discussed. 
@joshuaberetta, you could now review and merge it with the master branch.
> Updated article

- source/kobocollect-android.md
* Changed title
* Updated contents
* Minor formatting
@joshuaberetta, @c6reid cc: @Ig-Rebollo please be informed that I have updated this article as discussed.
@joshuaberetta, you could now review and merge it with the master branch.
> Updated article- Data Collection on KoboCollect app closes #146

- source/kobocollect_on_android_advanced.md
* Changed title
* Updated contents
* Fixed broken link
@joshuaberetta, @c6reid cc: @Ig-Rebollo please be informed that I have updated this article as discussed.
@joshuaberetta, you could now review and merge it with the master branch.
> Updated article- Advanced Data Collection on KoboCollect app

- source/library_locking.md
> Fix ibrary locking headings

- source/kobocollect-android.md
* Change the title of the support article from `Data Collection on KoBoCollect App - v1.30.1 and below` to `Data Collection on KoBoCollect App (Older Version)`.
* Minor formatting.
> Updated Data Collection on KoBoCollect older Closes #151

- .prettierrc.json
> Add prettierrc file for markdown

- source/_templates/layout.html
> Hide feedback from on 404

- scripts/last-updated.py
- source/index.rst
- source/recently_updated.md
`last-updated.py` extended to populate `source/recently_updated.md` with the 10 most recently edited support articles.
> Recently updated page and script

- scripts/last-updated.py
- source/merging_dataset_excel_power_query.md
- source/recently_updated.md
> Fix broken download link

- source/creating_account.md
- source/merging_dataset_excel_power_query.md
- source/recently_updated.md
Updated Troubleshooting Section for the existing article `Creating an account on KoboToolbox`.
> Closing #218 - Updated Troubleshooting Section

- source/new_form.md
- source/recently_updated.md
@joshuaberetta kindly review this. It's a minor update to the [Creating a New Form](https://support.kobotoolbox.org/getting_started_xlsform.html) article.
> Minor edits to "Creating a New Form"

- source/number_decimal_range.md
- source/recently_updated.md
@joshuaberetta I simply aligned-left the table you added at the end of the article. Kindly review and merge
> Minor Update number_decimal_range

- source/howto_edit_multiple_submissions.md
- source/recently_updated.md
> Add limitations regarding bulk-edits

- source/matrix_response.md
- source/recently_updated.md
> Update kobo matrix formatting

- source/_templates/layout.html
- source/conf.py
> Migrate to ga4

- source/_templates/partials/community_questions.html
Update to Community Questions section: copyedit for Community Forum CTA
Not sure if I did this one correctly - first time editing docs website
> Jess Update to community_questions.html

- source/question_library.md
See https://chat.kobotoolbox.org/#narrow/stream/6-Kobo-Support/topic/HTTP.20downloads.20in.20documentation
> Use HTTPS instead of HTTP for XLSForm download link

- source/encrypting_forms.md
Fixes 404 error; thanks to @Colprit for flagging in #350
> Update link to Oracle JCE

- source/getting_started_xlsform.md
> Getting started xlsform video

- source/_static/css/kobo_theme.css
Updated spacing and margins for lists in documentation pages + added space above headers
> Update margin styles for lists in kobo_theme.css
